<?php
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');
header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit();
}

// Load credentials from env file (generated by GitHub Actions)
$envFile = __DIR__ . '/.env.php';
if (file_exists($envFile)) {
    require_once $envFile;
}

$hostRaw = defined('DB_HOST') ? DB_HOST : 'localhost';
$db      = defined('DB_NAME') ? DB_NAME : 'afshxhoj_persianhub';
$user    = defined('DB_USER') ? DB_USER : 'afshxhoj_afshin';
$pass    = defined('DB_PASS') ? DB_PASS : '';

// Split host and port if given as "host:port"
if (strpos($hostRaw, ':') !== false) {
    [$host, $port] = explode(':', $hostRaw, 2);
} else {
    $host = $hostRaw;
    $port = '3306';
}

// Namecheap shared hosting requires 127.0.0.1 instead of localhost
if ($host === 'localhost') $host = '127.0.0.1';

try {
    $dsn = "mysql:host=$host;port=$port;dbname=$db;charset=utf8mb4";
    $pdo = new PDO($dsn, $user, $pass, [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_TIMEOUT            => 5,
    ]);
} catch (PDOException $e) {
    http_response_code(500);
    echo json_encode(['error' => 'Database connection failed', 'detail' => $e->getMessage()]);
    exit();
}
